@startuml
!$customAliasMap = [
    { "type": "actor",
      "name": "Пользователь",
      "alias": "user"
    },
    { "type": "participant",
      "name": "Ваш сервис",
      "alias": "srv",
      "order": "0"
    },
    { "type": "participant",
      "name": "Смежный сервис",
      "alias": "srv2",
      "order": "20"
    }
]