@startuml
!unquoted procedure metric($name)
    %invoke_procedure("metricController", $name)
!endprocedure

!unquoted procedure metricController($name)

    /'Проверка на уникальность для текущей диаграммы'/
    !$uniqueCurrentCheck = 0
    !foreach $item in $currentMetricMap
        !if $name == $item
            !$uniqueCurrentCheck = $uniqueCurrentCheck + 1
        !endif
    !endfor

    /'Проверка уникальности для пользовательских конфигов'/
    !$uniqueCheck = 0
    !foreach $item in $customMetricMap
        !if $name == $item
            !$uniqueCheck = $uniqueCheck + 1
        !endif
    !endfor

    /'Автозаполнение тудушки и сохранение новых конфигов'/
    !if $uniqueCurrentCheck == 0 && $uniqueCheck == 0
        !$todoText = "Необходимо добавить новую метрику: " + $name + ". Шаг: " + $id
        %invoke_procedure("todo", $todoText)
        !if $diagramMode == "final"
            %invoke_procedure("currentMetricMapBuilder",$name)
        !endif
    !endif

!endprocedure

!unquoted procedure currentMetricMapBuilder($name)
        !$currentMetricMap = %json_add($currentMetricMap, $name)
!endprocedure