@startuml
/'Список зависимостей'/
!unquoted procedure dependFrom($source="", $point="", $requirements="", $rds="", $duty="", $comment="", $status="")
    !if $source == ""
        !$i = $id - 1
        !$i = $linkOnOriginalSyntaxMap[$i]
        !$source = $originalSyntaxMap[$i].executor
    !endif

    !if $diagramMode == "final" && $status == ""
        !$temp = {}
        !$temp = %json_add($temp, "id", $id)
          !$temp = %json_add($temp, "source", $source)
        !$temp = %json_add($temp, "point", $point)
        !$temp = %json_add($temp, "requirements", $requirements)
        !$temp = %json_add($temp, "rds", $rds)
        !$temp = %json_add($temp, "duty", $duty)
        !$temp = %json_add($temp, "comment", $comment)
        !$temp = %json_add($temp, "status", $status)
        !$dependencyMap = %json_add($dependencyMap, $temp)
        %invoke_procedure("setOriginalSyntaxDependency", $source)
    !endif

    !if $status == "" && $lastDependencyId != $id
        %invoke_procedure("dependencyBuilder", $source)
        !$lastDependencyId = $id
    !endif
!endprocedure

!unquoted procedure setOriginalSyntaxDependency($source)
    !if $diagramMode == "final"
    !$temp = {}
    !$temp = %json_add($temp, "type", "dependency")
    !$temp = %json_add($temp, "layerId", $layerId)
    !$temp = %json_add($temp, "source", $source)
    !$originalSyntaxMap = %json_add($originalSyntaxMap, $temp)
    !$techId = $techId + 1
    !endif
!endprocedure

!unquoted procedure dependencyBuilder($source)
hnote over $source #yellow/red: <size:15><&fire> **ЗАВИСИМОСТЬ** <&fire>
!endprocedure

/'Построение строки со списком доработок'/
!unquoted procedure $dependencyRawBuilder()
    !$i = 0
    !foreach $item in $dependencyMap
    !$i = $i + 1
    !$dependOn = getNameByAlias($item.source)
| $i | $item.id | $dependOn | $item.point | $item.requirements | $item.rds | $item.duty | $item.comment | $item.status |
    !endfor
!endprocedure
/'TODO карта зависимостей строится некорректно, но конвертером обрабатывается'/

