@startuml
!unquoted procedure error($name)
    %invoke_procedure("errorController", $name)
!endprocedure

!unquoted procedure errorController($name)
    /'Проверка на уникальность для текущей диаграммы'/
    !$uniqueCurrentCheck = 0
    !foreach $item in $currentErrorMap
        !if $name == $item
            !$uniqueCurrentCheck = $uniqueCurrentCheck + 1
        !endif
    !endfor

    /'Проверка уникальности для пользовательских конфигов'/
    !$uniqueCheck = 0
    !foreach $item in $customErrorMap
        !if $name == $item
            !$uniqueCheck = $uniqueCheck + 1
        !endif
    !endfor

    /'Автозаполнение тудушки и сохранение новых конфигов'/
    !if $uniqueCurrentCheck == 0 && $uniqueCheck == 0
        !$todoText = "Необходимо добавить новую ошибку: " + $name + ". Шаг обнаружения: " + $id
        %invoke_procedure("todo", $todoText)
        !if $diagramMode == "final"
            %invoke_procedure("currentErrorMapBuilder",$name)
        !endif
    !endif
!endprocedure

!unquoted procedure currentErrorMapBuilder($name)
    !$currentErrorMap = %json_add($currentErrorMap, $name)
!endprocedure