@startuml
/'Построение диаграммы в оригинальном синтаксисе'/
!unquoted procedure ORIGINAL()
!$deviderEnabled = 1
note across
!if $diagramMode == "final"
/'Cтарт и стиль'/
%string("@"+"startuml")

/'Вывод параметров стиля'/
%invoke_procedure("styleController")

/'Вывод заголовки и хедера диаграммы'/
title Диаграмма: <color:blue>$sequenceName
header <color:black>with <color:blue>SequenceLib.v.4.0.<color:black> by PVR $originalBy

/'Участники и объединение в бокси'/
!foreach $item in $currentAliasMap
!if $item.box != 1
%invoke_procedure("partiesBuilder", $item.type, $item.name, $item.alias, $item.order)
!endif
!endfor
/'Боксы'/
!foreach $item in $originalSyntaxMap
!if $item.type == "box"
%invoke_procedure("BOX", $item.name, $item.color, $item.parties)
!endif
    /'Стрелки'/
!if $item.type == "action"
$tabMap[$item.layerId]%invoke_procedure("actionBuilder", $item.subtype, $item.initiator, $item.executor, $item.liveLine, $item.action)
!endif
    /'Зависимости'/
!if $item.type == "dependency"
$tabMap[$item.layerId]%invoke_procedure("dependencyBuilder", $item.source)
!endif
    /'Слои'/
!if $item.type == "layer"
$tabMap[$item.layerId]%invoke_procedure("layerBuilder", $item.subtype, $item.color, $item.description)
!endif
    /'Заметки'/
!if $item.type == "noteAndRef"
!if $item.subtype == "note"
!$color = colorController($item.color)
$tabMap[$item.layerId]%invoke_procedure("noteBuilder", $item.subtype, $item.position1, $item.position2, $color, $item.description)
!else
!$subtype = $item.subtype
!$color = colorController($item.color)
!$subtype = "ref" + $color
!$color = ""
$tabMap[$item.layerId]%invoke_procedure("refBuilder", $subtype, $item.position1, $item.position2, $color, $item.description)
!endif
!endif
    /'Аудит'/
!if $item.type == "audit"
$tabMap[$item.layerId]%invoke_procedure("auditBuilder", $item.name, $item.status, $item.source)
!endif
    /'Общие функции'/
!if $item.type == "activate" || $item.type == "deactivate" || $item.type == "separator"
$tabMap[$item.layerId]%invoke_procedure("commonBuilder", $item.type, $item.value)
!endif
!endfor
/'Легенда'/
%invoke_procedure("LEGEND")
/'Конец диаграммы'/
%string("@"+"enduml")
!else
** Генерация диаграммы в оригинальном синтаксисе доступна в режиме final **
!endif
end note
!endprocedure