@startuml
/'Список доработок'/
!unquoted procedure todo($td)
    !if $diagramMode == "final"
        !$temp = {}
        !$temp = %json_add($temp, "id", $id)
        !$temp = %json_add($temp, "todo", $td)
        !$todoMap = %json_add($todoMap, $temp)
    !endif
!endprocedure

/'Построение строки со списком доработок'/
!unquoted procedure todoRawBuilder()
    !$i = 0
    !foreach $item in $todoMap
    !$i = $i + 1
| $i | $item.id | $item.todo |
    !endfor
!endprocedure