@startuml
/'1. ПАРАМЕТРЫ И РУБИЛЬНИКИ
========================================================================================================================='/
/'Счетчики'/
!$id = 0    /'Счетчик стрелок'/
!$layerId = 0 /'Счетчик слоев: alt'/
!$bufferVar = "" /'Вспомогательная буфферная переменная'/
!$diagramMode = "" /'Режим работы библиотеки, draft/final'/
!$sequenceName = "" /'Заголовок диаграммы'/
!$deviderEnabled = 0

/'Сущности и объекты данных, создаваемые в текущей диаграмме'/
!$currentAliasMap = [] /'Участники текущей диаграммы'/
!$processMap = [] /'Карта процесса'/
!$originalSyntaxMap = [] /'Диаграмма в оригинальном синтаксисе'/
!$layerMap = [] /'Карта уровней/сценариев диаграммы'/
!$todoMap = [] /'Список доработок'/
!$currentAuditMap = [] /'Список событий аудита'/
!$currentConfigMap = [] /'Список параметров'/
!$currentMetricMap = [] /'Список метрик'/
!$currentErrorMap = [] /'Список ошибок'/

/'Параметры, ограничивающие длину строк в ячейках в таблице'/
!$actionLength = 20
!$commentLengthFinal = 35
!$commentLengthDraft = 60

/'Переменные с заголовками для легенды диаграммы'/
/'Карта процесса для разработчика, полная, с пояснениями'/
!$processMapFull = "| Код | ИC-инициатор | ИС-исполнитель | Тип взаимодействия | Тип сценария | Метод API | Описание |"

/'Таблица событий аудита'/
!$auditTable = "| # | Код события | Статус | Объект | Тип события | Операция | Краткое описание | Подробное описание | Доп.параметры |"

/'Выявленные в процессе моделирования доработки'/
!$todoList = "| № | id обнаружения | Суть доработки|"

/'Заголовок таблицы с описанием возможностей библиотеки'/
!$proceduresDescription = "| Наименование | Описание | Исходный синтаксис | Пример | Переменные |"

/'Таблица конфигурационных параметров'/
!$configTable = "| # | Наименование | Тип1 | Тип2 | Значение | Описание |"

/'Новые ошибки'/
!$errorTable = "| # | Метод | Ошибка | ИС источник | Маппинг в error.type 1673 | Стадия возникновения | Стадия в ответ для фронта | Параметры redirectUri | error&errorMessage | Заголовок | Текст |"

/'Новые метрики'/
!$metricTable = "| # | Наименование | Описание |"