@startuml
/'1. ПАРАМЕТРЫ И РУБИЛЬНИКИ
========================================================================================================================='/
/'Пользовательские настройки'/
!$author = "PVR"

!$proxyArrow = {"->":"Проксирование запроса","-->":"Проксирование ответа"}
!$arrowForLegend = {"->":"rq","-->":"rs"}

/'Счетчики'/
!$id = 0    /'Счетчик стрелок'/
!$techId = -1    /'Счетчик стрелок'/
!$layerId = 0 /'Счетчик слоев: alt'/
!$bufferVar = "" /'Вспомогательная буфферная переменная'/
!$diagramMode = "" /'Режим работы библиотеки, draft/final'/
!$sequenceName = "" /'Заголовок диаграммы'/
!$deviderEnabled = 0
!$orderId = 0 /'Счетчик участников'/

/'Сущности и объекты данных, создаваемые в текущей диаграмме'/
/'Объект: стрелка'/
!$actionObject = {}


!$currentAliasMap = [] /'Участники текущей диаграммы'/
!$originalSyntaxMap = [] /'Диаграмма в оригинальном синтаксисе'/
!$linkOnOriginalSyntaxMap = [] /'Ссылка на индекс в карте оригинального синтаксиса'/
!$layerMap = {"0":"default"} /'Карта уровней/сценариев диаграммы'/
!$todoMap = [] /'Список доработок'/
!$dependencyMap = [] /'Список зависимостей'/
!$currentAuditMap = [] /'Список событий аудита'/
!$currentConfigMap = [] /'Список параметров'/
!$currentMetricMap = [] /'Список метрик'/
!$currentErrorMap = [] /'Список ошибок'/
!$tabMap = {
"0" : "",
"1" : "    ",
"2" : "        ",
"3" : "            ",
"4" : "                ",
"5" : "                    ",
"6" : "                         "
}

/'Параметры, ограничивающие длину строк в ячейках в таблице'/
!$actionLength = 20
!$commentLengthFinal = 35
!$commentLengthDraft = 60

/'Переменные с заголовками для легенды диаграммы'/
/'Карта процесса для разработчика, полная, с пояснениями'/
!$processMapHead = [
"| Код | ИC-инициатор | ИС-исполнитель | Тип взаимодействия | Тип сценария | Метод API/ Действие | Описание |",
"|--|--|--|--|--|--|--|"
]

/'Таблица событий аудита'/
!$auditTableHead = ["| # | Код события | Статус | Объект | Тип события | Операция | Краткое описание | Подробное описание | Доп.параметры |",
"|--|--|--|--|--|--|--|--|--|"
]

/'Выявленные в процессе моделирования доработки'/
!$todoListHead = ["| № | id обнаружения | Суть доработки|",
"|--|--|--|"]

/'Заголовок таблицы с описанием возможностей библиотеки'/
!$proceduresDescription = ["| Наименование | Описание | Исходный синтаксис | Пример | Переменные |",
"|--|--|--|--|--|"]

/'Таблица конфигурационных параметров'/
!$configTableHead = ["| # | Наименование | Тип1 | Тип2 | Значение | Описание |",
"|--|--|--|--|--|--|"]

/'Новые ошибки'/
!$errorTableHead = ["| # | Метод | Ошибка | ИС источник | Маппинг в error.type 1673 | Стадия возникновения | Стадия в ответ для фронта | Параметры redirectUri | error&errorMessage | Заголовок | Текст |",
"|--|--|--|--|--|--|--|--|--|--|--|"]

/'Новые метрики'/
!$metricTableHead = ["| # | Наименование | Описание |",
"|--|--|--|"]

/'Карта зависимостей'/
!$dependencyMapHead = ["| i | id | source | point | requirements | rds | duty | comment | status |",
"|------|------|--------|-------|--------------|-----|------|---------|--------|"]