@startuml
/'Описание процедур'/
!$procHelpMap = [
{"name" : "rq",
"description" : "Рисует сплошную стрелку от участника-инициатора к участнику-исполнителю",
"originalSyntax" : "->",
"example" : "rq(initiator,executor,liveline,action,comment)",
"variables" : "initiator - инициатор,executor - исполнитель,liveline - линия жизни,action - текст над стрелкой,comment - текст комментария"},
{"name" : "rs",
"description" : "Рисует пунктирную стрелку от участника-инициатора к участнику-исполнителю",
"originalSyntax" : "-->",
"example" : "rs(initiator,executor,liveline,action,comment)",
"variables" : "initiator - инициатор,executor - исполнитель,liveline - линия жизни,action - текст над стрелкой,comment - текст комментария"},
{"name" : "parties",
"description" : "Рисует участников диаграммы",
"originalSyntax" : "participant имя as алиас order",
"example" : "parties(type,name,as,order)",
"variables" : "type - тип участника,name - имя участника,as - вспомогательная переменная,order - порядок расположения"},
{"name" : "audit",
"description" : "Рисует нотификацию об отправке события в аудит",
"originalSyntax" : "-",
"example" : "audit(event,status,desc,participant)",
"variables" : "event - имя события,status - статус, может быть пустым,desc - описание для таблицы,participant - линия участника, на которой будет отображена нотификация"},
{"name" : "anc",
"description" : "Якорь, запоминает текущее значение autonumber",
"originalSyntax" : "-",
"example" : "anchor(name)",
"variables" : "name - имя якоря"},
{"name" : "BOX",
"description" : "Рисует объединение участников в бокс",
"originalSyntax" : "box nameBox color",
"example" : "BOX(name,color, участник1|участник2)",
"variables" : "name - наименование бокса,color - цвет бокса, список участников через запятую"},
{"name" : "ALT",
"description" : "Рисует выделение альтернативного сценария",
"originalSyntax" : "alt color case",
"example" : "ALT(color,description",
"variables" : "color - цвет кейса,description - описание кейса"},
{"name" : "OPT",
"description" : "Рисует выделение опционального сценария",
"originalSyntax" : "opt color case",
"example" : "OPT(color,description",
"variables" : "color - цвет кейса,description - описание кейса"},
{"name" : "PAR",
"description" : "Рисует выделение параллельного сценария",
"originalSyntax" : "par color case",
"example" : "PAR(color,description",
"variables" : "color - цвет кейса,description - описание кейса"},
{"name" : "GROUP",
"description" : "Рисует выделение сгруппированного сценария",
"originalSyntax" : "group color case",
"example" : "GROUP(color,description",
"variables" : "color - цвет кейса,description - описание кейса"},
{"name" : "LOOP",
"description" : "Рисует выделение цикличного сценария",
"originalSyntax" : "loop color case",
"example" : "LOOP(color,description",
"variables" : "color - цвет кейса,description - описание кейса"},
{"name" : "ELSE",
"description" : "Рисует выделение альтернативного сценария",
"originalSyntax" : "elst color case",
"example" : "ELSE(color,description",
"variables" : "color - цвет кейса,description - описание кейса"},
{"name" : "END",
"description" : "Закрывает альты, опты и тд",
"originalSyntax" : "end",
"example" : "END()",
"variables" : "-"},
{"name" : "NOTE",
"description" : "Рисует заметку в заданном месте",
"originalSyntax" : "note across: или note over participant:",
"example" : "NOTE(position1,position2,color,description)",
"variables" : "position1,position2 - управляют положением заметки,color - цвет фона заметки,description - содержание, текст заметки"},
{"name" : "REF",
"description" : "Рисует ссылку в заданном месте",
"originalSyntax" : "ref across: или ref over participant:",
"example" : "REF(position1,position2,color,description)",
"variables" : "position1,position2 - управляют положением ссылки, color - цвет фона ссылки, description - содержание, текст ссылки"},
{"name" : "ACTIVATE",
"description" : "Рисует линию жизни участника",
"originalSyntax" : "activate participantname",
"example" : "ACTIVATE(party)",
"variables" : "party - алиас участника"},
{"name" : "DEACTIVATE",
"description" : "Завершает линию жизни участника",
"originalSyntax" : "deactivate participantname",
"example" : "DEACTIVATE(party)",
"variables" : "party - алиас участника"},
{"name" : "diagramInit",
"description" : "Инициирует диаграмма, рисует заголовок с параметрами",
"example" : "diagramInit(draft,name)",
"variables" : "mode - режим работы для постановок (draft, final), name - заголовок диаграммы"},
{"name" : "LEGEND",
"description" : "Рисует легенду диаграммы в зависимости от режима работы",
"originalSyntax" : "-",
"example" : "LEGEND()",
"variables" : "-"},
{"name" : "ORIGINAL",
"description" : "Генерирует заметку с исходным синтаксисом",
"originalSyntax" : "-",
"example" : "ORIGINAL()",
"variables" : "-"},
{"name" : "HELP",
"description" : "Генерирует заметку с описанием процедур",
"originalSyntax" : "-",
"example" : "HELP(procName)",
"variables" : "procName - имя процедуры, если пустое показывает все"}
]